version: "2"
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: .
    ports:
      - "7770:7770"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
    depends_on:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
