version: "2"
services:
  app:
    build: .
    ports:
      - "7770:7770"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /Users/chrisholmes/data/mongodb/db:/data/db
    ports:
      - "27017:27017"
